const productData = [
    {
        prodID: 19,
        prodName: "Cartoon Shirt",
        prodAdress: "img/products/f1.jpg",
        prodBrand: "Adidas",
        categories: ["men", "shirts", "featured"],
        prodPrice: 78,
    },
    {
        prodID: 28,
        prodName: "Garden Shirt",
        prodAdress: "img/products/f2.jpg",
        prodBrand: "Balenciaga",
        categories: ["men", "shirts"],
        prodPrice: 578,
    },
    {
        prodID: 37,
        prodName: "Havian Shirt",
        prodAdress: "img/products/f3.jpg",
        prodBrand: "Chanel",
        categories: ["men", "shirts", "featured"],
        prodPrice: 111,
    },
    {
        prodID: 46,
        prodName: "F***Boy Shirt",
        prodAdress: "img/products/f4.jpg",
        prodBrand: "Prada",
        categories: ["men", "shirts", "featured"],
        prodPrice: 265,
    },
    {
        prodID: 55,
        prodName: "Emo-Boy Shirt",
        prodAdress: "img/products/f5.jpg",
        prodBrand: "GAP",
        categories: ["men", "shirts", "featured"],
        prodPrice: 99,
    },
    {
        prodID: 64,
        prodName: "Virginity Screamer Shirt",
        prodAdress: "img/products/f6.jpg",
        prodBrand: "None",
        categories: ["men", "shirts"],
        prodPrice: 8,
    },
    {
        prodID: 73,
        prodName: "Pants",
        prodAdress: "img/products/f7.jpg",
        prodBrand: "H3H3",
        categories: ["women", "pants"],
        prodPrice: 875,
    },
    {
        prodID: 82,
        prodName: "Shirt",
        prodAdress: "img/products/f8.jpg",
        prodBrand: "H3H3",
        categories: ["women", "shirts"],
        prodPrice: 987,
    },
    {
        prodID: 109,
        prodName: "Light Blue Dress Shirt",
        prodAdress: "img/products/n1.jpg",
        prodBrand: "H3H3",
        categories: ["men", "shirts"],
        prodPrice: 90,
    },
    {
        prodID: 208,
        prodName: "Light Gray Checkered Dress Shirt",
        prodAdress: "img/products/n2.jpg",
        prodBrand: "H3H3",
        categories: ["men", "shirts"],
        prodPrice: 102,
    },
    {
        prodID: 307,
        prodName: "Off White Dress Shirt",
        prodAdress: "img/products/n3.jpg",
        prodBrand: "H3H3",
        categories: ["men", "shirts", "featured"],
        prodPrice: 76,
    },
    {
        prodID: 406,
        prodName: "Camo Casual Shirt",
        prodAdress: "img/products/n4.jpg",
        prodBrand: "H3H3",
        categories: ["men", "shirts"],
        prodPrice: 55,
    },
    {
        prodID: 505,
        prodName: "Denim Full Sleeves Shirt",
        prodAdress: "img/products/n5.jpg",
        prodBrand: "H3H3",
        categories: ["women", "shirts"],
        prodPrice: 145,
    },
    {
        prodID: 604,
        prodName: "Dress Shorts ??",
        prodAdress: "img/products/n6.jpg",
        prodBrand: "H3H3",
        categories: ["men", "pants"],
        prodPrice: 35,
    },
    {
        prodID: 703,
        prodName: "Wheatish Brown Dress Shirt",
        prodAdress: "img/products/n7.jpg",
        prodBrand: "H3H3",
        categories: ["men", "shirts"],
        prodPrice: 260,
    },
    {
        prodID: 802,
        prodName: "Dark Gray Button Up Shirt",
        prodAdress: "img/products/n8.jpg",
        prodBrand: "H3H3",
        categories: ["men", "shirts"],
        prodPrice: 120,
    },
    {
        prodID: 110,
        prodName: "Green Cargo Pants",
        prodAdress: "img/products/p1.jpg",
        prodBrand: "H3H3",
        categories: ["men", "pants", "featured"],
        prodPrice: 290,
    },
    {
        prodID: 115,
        prodName: "Blue Cargo Pants",
        prodAdress: "img/products/p2.jpg",
        prodBrand: "H3H3",
        categories: ["men", "pants", "featured"],
        prodPrice: 270,
    },
    {
        prodID: 120,
        prodName: "Maroon Chinos",
        prodAdress: "img/products/p3.jpg",
        prodBrand: "H3H3",
        categories: ["men", "pants"],
        prodPrice: 190,
    },
    {
        prodID: 125,
        prodName: "Black Dress Pants",
        prodAdress: "img/products/p4.jpg",
        prodBrand: "H3H3",
        categories: ["men", "pants"],
        prodPrice: 200,
    },
    {
        prodID: 130,
        prodName: "Brown Cargo Pants",
        prodAdress: "img/products/p5.jpg",
        prodBrand: "H3H3",
        categories: ["men", "pants", "featured"],
        prodPrice: 230,
    },
    {
        prodID: 135,
        prodName: "White long Pants",
        prodAdress: "img/products/w1.jpg",
        prodBrand: "H3H3",
        categories: ["women", "pants"],
        prodPrice: 310,
    },
    {
        prodID: 140,
        prodName: "Blue Denim Pants",
        prodAdress: "img/products/w2.jpg",
        prodBrand: "H3H3",
        categories: ["women", "pants"],
        prodPrice: 250,
    },
    {
        prodID: 145,
        prodName: "Brown Casual Pants",
        prodAdress: "img/products/w3.jpg",
        prodBrand: "H3H3",
        categories: ["women", "pants"],
        prodPrice: 180,
    },
    {
        prodID: 150,
        prodName: "Off White Long Pants",
        prodAdress: "img/products/w4.jpg",
        prodBrand: "H3H3",
        categories: ["women", "pants"],
        prodPrice: 310,
    },
    {
        prodID: 155,
        prodName: "Bright Red Pants",
        prodAdress: "img/products/w5.jpg",
        prodBrand: "H3H3",
        categories: ["women", "pants"],
        prodPrice: 210,
    },
];

module.exports = productData;
